name: Build/Deploy on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go get

      - run: go build
